### PR TITLE
make memory and other settings configurable

### PR DESCRIPTION
**Pull request by feniix**
This PR makes some settings of the collector configurable using environment variables which help deploy the collector in situations like kubernetes or mesos

### CODE REVIEW

**Comment by duchatran** [comment]
Thanks! @feniix: is there a particular reason you switched from ENTRYPOINT to CMD? We used ENTRYPOINT to pass in extra parameters to run.sh when running the container (these parameters can change in the future).

**Comment by feniix** [comment]
@duchatran IMHO entrypoint should be used when the script that it calls is a "wrapper" such as a bash script that if you pass a specific parameter it behaves in a special way (see [docker-entrypoint.sh](https://github.com/docker-library/mysql/blob/master/5.6/docker-entrypoint.sh#L32)) otherwise it is too opaque and you need to do a `docker inspect` and actually have the source of the container to change the behaviour.

overriding the cmd is a lot easier and straightforward. (that is, IMO)

**Comment by stevezau** [comment]
+1 for this.. any updates?

**Comment by stevezau** [comment]
@feniix think this PR is missing updates to the readme

**Comment by feniix** [comment]
@stevezau @duchatran I have added the documentation

**Comment by stevezau** [comment]
@feniix I decided to support all options.. See this https://github.com/SumoLogic/sumologic-collector-docker/pull/27

I think it makes your PR not required?

**Comment by stevezau** [comment]
except the debug logging and stdout.. maybe i'll add that also

**Comment by feniix** [comment]
@stevezau yeah we can close this one

**Pull request closed without merging**
